<?php

/**
 * @param $variables
 * Implements hook_preprocess_page()
 */
function library_ex_preprocess_page(&$variables){

  # Подключили библиотеку на страницу с NID = 1
  $current_path = \Drupal::service('path.current')->getPath();
  
  if(explode('/', $current_path)[1]=='node' && is_numeric(explode('/', $current_path)[2])==true){
    $variables['#attached']['library'][] =  'library_ex/library_ex';
	
  }


}
